import { Colors } from "react-native/Libraries/NewAppScreen";
import { COLORS, SIZES } from "../helper/constants";

const { StyleSheet } = require("react-native");

const styles =  StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:COLORS.lightwhite
    },
    upperRow:{
        marginHorizontal:20,
        flexDirection:'row',
        justifyContent:"space-between",
        alignItems:"center",
        position:'absolute',
        top:SIZES.xxlarge,
        width:SIZES.width-44,
        zIndex:999
    },
    image:{
        aspectRatio:1,
        resizeMode:'cover'
    },
    details:{
        marginTop:-SIZES.large,
        backgroundColor:COLORS.lightwhite,
        width:SIZES.width,
        borderRadius:SIZES.medium,
        borderTopRightRadius:SIZES.medium
    },
    titleRow:{
        marginHorizontal:20,
        paddingBottom:SIZES.small,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        width:SIZES.width-44,
        top:20
    },
    title:{
        width:'70%',
         fontWeight:"bold",
         fontSize:SIZES.xlarge
    },
    priceWrapper:{
        backgroundColor:COLORS.secondary,
        borderRadius:SIZES.large
    },
    price:{
        paddingHorizontal:10,
        fontWeight:"bold",
        fontSize:SIZES.xlarge
    },
    cartRow:{
        paddingBottom:SIZES.small,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        width:SIZES.width,
        top:20
    },
    cartBtn:{
        width:SIZES.width*0.7,
        backgroundColor:"black",
        padding:SIZES.small/2,
        borderRadius:SIZES.large,
        marginLeft:12
    },
    cartTitle:{
        marginLeft:SIZES.small,
        fontWeight:"bold",
        fontSize:SIZES.medium,
        color:COLORS.lightwhite
   },
   addCart:{
    paddingTop:5,
    borderRadius:37/2,
    width:37,
    height:37,
    margin:SIZES.small,
    backgroundColor:"black",
    alignItems:'center'
   },

    ratingRow:{
        paddingBottom:SIZES.small,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        width:SIZES.width-10,
        top:5
    },
    rating:{
        top:SIZES.large,
        flexDirection:'row',
        justifyContent:"flex-start",
        alignItems:'center',
        marginHorizontal:SIZES.large,
        paddingHorizontal:SIZES.xsmall
    },
    ratingText:{
        paddingHorizontal:SIZES.xsmall,
        color:COLORS.gray,
        fontWeight:"600",
    },
    descriptionWrapper:{
        marginTop:SIZES.large*2,
        marginHorizontal:SIZES.large
    },
    description:{
        fontWeight:"700",
        fontSize:SIZES.xlarge-2
    },
    descText:{
        fontSize:SIZES.small,
        textAlign:"justify",
        marginBottom:SIZES.small
    },
    location:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        backgroundColor:COLORS.secondary,
        padding:5,
        borderRadius:SIZES.large
    }
})

export default styles;